image:
  repository: "docker-registry-simulation.lab.zjvis.net:32443/docker.io/library/influxdb"
  tag: "1.8.10-alpine"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  nodePorts:
    http: ""
persistence:
  enabled: true
  storageClass: "nfs-external-nas"
  annotations:
  accessMode: ReadWriteOnce
  size: 50Gi
setDefaultUser:
  enabled: true
