password: "j1bKEKPOMm"
persistence:
  storageClass: "nfs-external-nas"
  size: 50Gi
redis:
  configmap: |-
    maxmemory-policy allkeys-lru
    maxmemory 50GB
  useAOFPersistence: "no"
cluster:
  nodes: 6
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      port: 6379
      loadBalancerIP:
        - 10.105.20.141
        - 10.105.20.142
        - 10.105.20.143
        - 10.105.20.144
        - 10.105.20.145
        - 10.105.20.146
      annotations:
        purelb.io/service-group: purelb-layer2-ippool
image:
  registry: docker-registry-simulation.lab.zjvis.net:32443/docker.io
  repository: bitnami/redis-cluster
  tag: 6.2.2-debian-10-r0
  pullPolicy: IfNotPresent
metrics:
  image:
    registry: docker-registry-simulation.lab.zjvis.net:32443/docker.io
    repository: bitnami/redis-exporter
    tag: 1.20.0-debian-10-r27
    pullPolicy: IfNotPresent
