replicas: 1
image:
  registry: docker-registry-simulation.lab.zjvis.net:32443/docker.io
  repository: grafana/grafana
  tag: "9.2.15"
  pullPolicy: IfNotPresent
testFramework:
  enabled: true
  image: docker.io/bats/bats
  tag: "v1.4.1"
  imagePullPolicy: IfNotPresent
downloadDashboardsImage:
  registry: docker-registry-simulation.lab.zjvis.net:32443/docker.io
  repository: curlimages/curl
  tag: 7.85.0
  pullPolicy: IfNotPresent
service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  pathType: ImplementationSpecific
  hosts:
    - grafana-simulation.cnconti.cc
persistence:
  type: pvc
  enabled: true
  storageClassName: "nfs-external-nas"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
initChownData:
  enabled: true
  image:
    registry: docker-registry-simulation.lab.zjvis.net:32443/docker.io
    repository: library/busybox
    tag: "1.31.1"
    pullPolicy: IfNotPresent
adminUser: admin
adminPassword: AAaa1234
sidecar:
  image:
    registry: docker-registry-simulation.lab.zjvis.net:32443/quay.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.22.0
  imagePullPolicy: IfNotPresent
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"
imageRenderer:
  enabled: false
networkPolicy:
  enabled: false
